stages:
  - build_web
  - build_nginx
  - deploy

docker_build_web:
  stage: build_web
  script:
    - export VERSION=$(grep "VERSION=" .env | cut -d= -f2 | head -1)
    - echo "Build docker image web"
    - docker build -t web:$VERSION .
    - echo "Push docker image to Nexus"
    #- docker push my_nexus.ru/web#
  only:
    refs:
        - chnanges
    changes:
        - Dockerfile
  tags:
    - runner
 
docker_build_nginx: 
  stage: buid_nginx
  script:
    - echo "Build docker image nginx"
    - docker build -t nginx:latest -f nginx/Dockerfile nginx/.
    - echo "Push docker image to Nexus"
    #- docker push my_nexus.ru/nginx#
  only:
    refs:
        - chnanges
    changes:
        - nginx/Dockerfile
  tags:
    - runner

deploy to webserver:
  stage: deploy
  script:
     - echo "Deploy to docker-compose"
     - sshpass -p "$PASS" scp -o StrictHostKeyChecking=no -r docker-compose.yml user@webserver:/opt/ci/
     - sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no user@webserver "/opt/ci/deploy.sh"
  tags:
    - runner

