stages:
  - build_web
  - build_nginx
  - deploy

docker_build_web:
  stage: build_web
  script:
    - export VERSION=$(grep "VERSION=" .env | cut -d= -f2 | head -1)
    - echo "Build docker image web"
    - docker build -t web:$VERSION .
    - echo "Push docker image to Nexus"
    #- docker push my_nexus.ru/web#
  only:
    refs: 
        - changes
    changes: 
        - Dockerfile
        - weeman/*.py
        - weeman/**/*.py
      
  tags:
    - runner
 
docker_build_nginx: 
  stage: buid_nginx
  script:
    - echo "Build docker image nginx"
    - docker build -t nginx:latest -f nginx/Dockerfile nginx/.
    - echo "Push docker image to Nexus"
    #- docker push my_nexus.ru/nginx#   
  only:
    refs: 
        - changes
    changes: 
        - nginx/Dockerfile
        - nginx/nginx.conf
  tags:
    - runner

