# set base image (host OS)
FROM nginx

# set the working directory in the container
WORKDIR /etc/nginx

# copy the config of the local src directory to the working directory
ADD nginx.conf /etc/nginx/conf.d/default.conf
